### ISSUE TITLE
SzContext in bigsur have lags when open context menu

### ISSUE THREAD

**Issue by RoadToDream** [RoadToDream/SzContext#1]
Reported by @reslear 
<img width="914" alt="image" src="https://user-images.githubusercontent.com/8088354/103182015-70b47d80-485c-11eb-9f73-c51dbc51c29f.png">

**Comment by reslear** [comment]
big sur 11.0.1
SzContext 0.3

1. lags
2. position on bottom 
3. not closing window on set true checkbox, in Settings - Extensions "Finder extension" 

https://user-images.githubusercontent.com/12596485/103182132-0b8f7500-48ba-11eb-8581-63ad1cca85c3.mov

**Comment by reslear** [comment]
v0.4 lags fixed, thank you @RoadToDream )

**Comment by RoadToDream** [comment]
> big sur 11.0.1
> 
> SzContext 0.3
> 
> 
> 
> 1. lags
> 
> 2. position on bottom 
> 
> 3. not closing window on set true checkbox, in Settings - Extensions "Finder extension" 
> 
> 
> 
> https://user-images.githubusercontent.com/12596485/103182132-0b8f7500-48ba-11eb-8581-63ad1cca85c3.mov
> 
> 

Hi reslear, 
I believe the first two issues could be fixed after a restart. 
And I am sorry that I am not sure what do you mean by the third problem.

**Comment by reslear** [comment]
close SzContext info window when set checkbox in setting) 
that optional, mini ux)

**Comment by RoadToDream** [comment]
> close SzContext info window when set checkbox in setting) 
> 
> that optional, mini ux)
> 
> 

I got what you mean, will be added in next version.

**Comment by RoadToDream** [comment]
@reslear We have released a new version with better UI, hope you would like it.

**Comment by RoadToDream** [comment]
[v0.5](https://github.com/RoadToDream/SzContext/releases/download/0.5/SzContext.dmg)
This version rewrites the app completely, so there might be some bugs. Go have a try if you are interested.

**Comment by reslear** [comment]
> [v0.5](https://github.com/RoadToDream/SzContext/releases/download/0.5/SzContext.dmg)
> This version rewrites the app completely, so there might be some bugs. Go have a try if you are interested.

wow nice interface, maybe add button for restart Finder ?)

**Comment by RoadToDream** [comment]
> > [v0.5](https://github.com/RoadToDream/SzContext/releases/download/0.5/SzContext.dmg)
> 
> > This version rewrites the app completely, so there might be some bugs. Go have a try if you are interested.
> 
> 
> 
> wow nice interface, maybe add button for restart Finder ?)

I think the extension should be automatically enabled if it's the first time to set it up. I would consider add an option to force load it.
