### ISSUE TITLE
Link to App Store doesn't work

### ISSUE THREAD

**Issue by agnusha** [RoadToDream/SzContext#10]
<img width="258" alt="image" src="https://github.com/user-attachments/assets/21248577-dd95-4abf-bbeb-6e908e9f96a4">

**Comment by RoadToDream** [comment]
Hi, thanks for your interest in this app, unfortunately I no longer subscribe to Apple's developer program. They don't provide that in the store anymore. You may download the latest release from GitHub, check the source code and recompile if you have security concerns.
