### ISSUE TITLE
SzContext significant energy usage on M1 MacBook pro

### ISSUE THREAD

**Issue by vanderwijk** [RoadToDream/SzContext#7]
Hi, I just noticed that MacOS 11.2.1 is reporting significant energy usage by ScContext on my M1 MacBook Pro. Overall it does not seem to dramatically drain the battery but I do find it surprising that this is happening with a relatively simple app.

<img width="343" alt="Schermafbeelding 2021-02-14 om 13 40 33" src="https://user-images.githubusercontent.com/1212909/107877179-1edabc00-6ecb-11eb-8ef3-874b83303edb.png">

Any ideas why this is happening and how to fix this?

**Comment by RoadToDream** [comment]
> Hi, I just noticed that MacOS 11.2.1 is reporting significant energy usage by ScContext on my M1 MacBook Pro. Overall it does not seem to dramatically drain the battery but I do find it surprising that this is happening with a relatively simple app.
> 
> <img alt="Schermafbeelding 2021-02-14 om 13 40 33" width="343" src="https://user-images.githubusercontent.com/1212909/107877179-1edabc00-6ecb-11eb-8ef3-874b83303edb.png">
> 
> Any ideas why this is happening and how to fix this?

Hi!
Sorry to see that happened, unfortunately I do not have an M1 device and unable to test that, but my guess is that SzContext requires a background XPC service and it may result in such a way. Generally SzContext should not consume any energy as long as you will not do any action from the context menu. 
I have noticed that you mentioned it will not drain battery life noticeably, and that should match my guess. 

If you are interested in solving the issue, would you like to provide a screenshot of Activity monitor that shows CPU usage of all process which names contain "szcontext"? Just like the screenshot I attached. 

<img width="1552" alt="Screen Shot 2021-02-15 at 9 43 00 AM" src="https://user-images.githubusercontent.com/8088354/107978840-52245600-6f72-11eb-8b05-6cb1014d865d.png">

**Comment by vanderwijk** [comment]
I have made some screenshots of the activitymonitor (in Dutch unfortunately) and it indeed seems that SzContext isn't actually using a lot of power, but all other programs just use very little power 😄

<img width="1204" alt="Schermafbeelding 2021-02-16 om 10 19 21" src="https://user-images.githubusercontent.com/1212909/108043125-fe347280-7040-11eb-89cf-e419ad4cecd4.png">
<img width="1204" alt="Schermafbeelding 2021-02-16 om 10 19 45" src="https://user-images.githubusercontent.com/1212909/108043131-0096cc80-7041-11eb-856c-7b492fd439fa.png">
<img width="1204" alt="Schermafbeelding 2021-02-16 om 10 20 21" src="https://user-images.githubusercontent.com/1212909/108043132-01c7f980-7041-11eb-944c-0eef57158565.png">

**Comment by RoadToDream** [comment]
> I have made some screenshots of the activitymonitor (in Dutch unfortunately) and it indeed seems that SzContext isn't actually using a lot of power, but all other programs just use very little power 😄
> 
> 
> 
> <img width="1204" alt="Schermafbeelding 2021-02-16 om 10 19 21" src="https://user-images.githubusercontent.com/1212909/108043125-fe347280-7040-11eb-89cf-e419ad4cecd4.png">
> 
> <img width="1204" alt="Schermafbeelding 2021-02-16 om 10 19 45" src="https://user-images.githubusercontent.com/1212909/108043131-0096cc80-7041-11eb-856c-7b492fd439fa.png">
> 
> <img width="1204" alt="Schermafbeelding 2021-02-16 om 10 20 21" src="https://user-images.githubusercontent.com/1212909/108043132-01c7f980-7041-11eb-944c-0eef57158565.png">
> 
> 
> 
> 
> 
> 

Developers like me who is still using Intel based Mac may not anticipate that coming 🤔 
Will look into it see if I may resolve this problem, but till now I may not have any good ideas as I have tried my best to minimize SzContext's power consumption. (I use it everyday so even just for my own good I would not like it to be a battery glutton)

But thank you very much for the detailed info, and I will try to provide a fix.

**Comment by RoadToDream** [comment]
Hi, @vanderwijk , after purchasing a M2 MBA and using for some time, I can't reproduce this issue now. Not sure if you are still using the app, but if this issue still occurred frequently, just let me know and I may investigate more.

**Comment by vanderwijk** [comment]
I am no longer seeing the hight energy usage so this seems to be solved. I'm closing the issue!
