### ISSUE TITLE
Feature: quick option on touch bar

### ISSUE THREAD

**Issue by varunkudalkar** [RoadToDream/SzContext#8]
We should have a quick action menu on the touch bar.

**Comment by RoadToDream** [comment]
> We should have a quick action menu on the touch bar.

Hi @varunkudalkar !
Glad to hear from you. 
May I ask if you want the quick action menu on the Touch Bar all the time?

**Comment by varunkudalkar** [comment]
Not for all the time, because as a default behavior of touch bar action menu should change as per the applications opened in the window.
For example, if the finder window is opened and one of the folders is selected then we can have an action button to open the terminal with the selected folder path.

**Comment by RoadToDream** [comment]
> Not for all the time, because as a default behavior of touch bar action menu should change as per the applications opened in the window.
> 
> For example, if the finder window is opened and one of the folders is selected then we can have an action button to open the terminal with the selected folder path.

I think I will consider add that in the next release. But it may not be possible to have touch-bar button shown only under some conditions. (System limitations) 
An always shown touch-bar item is possible.

**Comment by RoadToDream** [comment]
Hi @varunkudalkar, as Touch Bar doesn't seem to be supported in the future, I will not consider adding this feature at the moment. Will see if there is any changes. 
Closing the issue for now.
