### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by Beelink** [RoadToDream/SzContext#9]
Hi.
I have developed few open-source apps ([example](https://moduleart.github.io/quick-picture-viewer/)) and now I want to build a website where I can place them. I see that your app doesn't have a website. So, can I place your app on my [website](https://moduleart.github.io/)? Just because I like your app and I use it as my daily driver.
Thanks =)

Some screenshots:

![image](https://user-images.githubusercontent.com/40366303/147862805-807b0640-111b-44e3-adbb-59bbfb0a28fd.png)
![image](https://user-images.githubusercontent.com/40366303/147862876-a283ee6c-40b3-49c8-b428-27184a649086.png)

**Comment by RoadToDream** [comment]
Hi @Beelink , thank you for liking my app. Sure you may add it to your website as you wish. 
I am currently not active on GitHub, sorry for the late reply. 
Best

**Comment by Beelink** [comment]
Hey @RoadToDream, I forgot to send you a link to the website 😅
https://moduleart.github.io/szcontext

Let me know if you want to add the "Donate" button that will follow to a donation service of choice:
OpenCollective, Patreon, PayPal, etc.
Do you have such a link?
